chore: 환경변수 복원을 위한 workflow 수정

diff --git a/.github/workflows/frontend_prod_macmini.yml b/.github/workflows/frontend_prod_macmini.yml
--- a/.github/workflows/frontend_prod_macmini.yml
+++ b/.github/workflows/frontend_prod_macmini.yml
@@ -17,30 +17,30 @@ jobs:
 
       - name: Create .env file
         run: |
-          echo "NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL_PROD }}" > .env
-          echo "NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL_PROD }}" >> .env
-          echo "NEXT_PUBLIC_GA_ID=${{ secrets.NEXT_PUBLIC_GA_ID_PROD }}" >> .env
-          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> .env
-          echo "NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}" >> .env
-          echo "DEEPL_API_KEY=${{ secrets.DEEPL_API_KEY }}" >> .env
-          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
+          echo "NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL_PROD }}" > ~/jumo/.env
+          echo "NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL_PROD }}" >> ~/jumo/.env
+          echo "NEXT_PUBLIC_GA_ID=${{ secrets.NEXT_PUBLIC_GA_ID_PROD }}" >> ~/jumo/.env
+          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> ~/jumo/.env
+          echo "NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}" >> ~/jumo/.env
+          echo "DEEPL_API_KEY=${{ secrets.DEEPL_API_KEY }}" >> ~/jumo/.env
+          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> ~/jumo/.env
 
-      - name: Build Docker image
-        run: |
-          docker build -t macmini/jumo_front_prod:latest .
+      # - name: Build Docker image
+      #   run: |
+      #     docker build -t macmini/jumo_front_prod:latest .
 
-      - name: Stop existing Docker container (if running)
-        run: |
-          docker stop $(docker ps -q) || true
+      # - name: Stop existing Docker container (if running)
+      #   run: |
+      #     docker stop $(docker ps -q) || true
 
-      - name: Run Docker container
-        run: |
-          docker run --rm -it -d -p 80:3000 \
-            -e SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} \
-            -e DEEPL_API_KEY=${{ secrets.DEEPL_API_KEY }} \
-            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
-            --name jumo_front_prod macmini/jumo_front_prod:latest
+      # - name: Run Docker container
+      #   run: |
+      #     docker run --rm -it -d -p 80:3000 \
+      #       -e SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} \
+      #       -e DEEPL_API_KEY=${{ secrets.DEEPL_API_KEY }} \
+      #       -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
+      #       --name jumo_front_prod macmini/jumo_front_prod:latest
 
-      - name: Clean up unused Docker images
-        run: |
-          docker image prune -a -f || true
+      # - name: Clean up unused Docker images
+      #   run: |
+      #     docker image prune -a -f || true
