az1 제거

diff --git a/.github/workflows/frontend_prod.yml b/.github/workflows/frontend_prod.yml
--- a/.github/workflows/frontend_prod.yml
+++ b/.github/workflows/frontend_prod.yml
@@ -41,36 +41,37 @@ jobs:
           docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/jumo_front_prod:latest .
           docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/jumo_front_prod:latest
 
-  deploy-to-az1:
-    needs: build-docker-image
-    runs-on: [prod, 2a]
-    strategy:
-      max-parallel: 1
-    steps:
-      - name: ecr get-login-password
-        run: |
-          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/jumo_front_prod
-      - name: Pull Docker image from AWS ECR
-        run: |
-          docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/jumo_front_prod:latest
+  # deploy-to-az1:
+  #   needs: build-docker-image
+  #   runs-on: [prod, 2a]
+  #   strategy:
+  #     max-parallel: 1
+  #   steps:
+  #     - name: ecr get-login-password
+  #       run: |
+  #         aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/jumo_front_prod
+  #     - name: Pull Docker image from AWS ECR
+  #       run: |
+  #         docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/jumo_front_prod:latest
 
-      - name: stop Docker container before running new container
-        run: |
-          sudo docker stop $(sudo docker ps -aq) || true
+  #     - name: stop Docker container before running new container
+  #       run: |
+  #         sudo docker stop $(sudo docker ps -aq) || true
 
-      - name: Run new Docker container
-        run: |
-          docker run --rm -it -d -p 80:3000 \          
-          -e SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} \
-          -e DEEPL_API_KEY=${{ secrets.DEEPL_API_KEY }} \
-          --name jumo_front_prod ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/jumo_front_prod:latest
+  #     - name: Run new Docker container
+  #       run: |
+  #         docker run --rm -it -d -p 80:3000 \          
+  #         -e SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} \
+  #         -e DEEPL_API_KEY=${{ secrets.DEEPL_API_KEY }} \
+  #         --name jumo_front_prod ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/jumo_front_prod:latest
 
-      - name: Clean up unused Docker images after deployment
-        run: |
-          sudo docker image prune -a -f || true
+  #     - name: Clean up unused Docker images after deployment
+  #       run: |
+  #         sudo docker image prune -a -f || true
 
   deploy-to-az2:
-    needs: deploy-to-az1
+    # needs: deploy-to-az1
+    needs: build-docker-image
     runs-on: [prod, 2c]
     strategy:
       max-parallel: 1
